name: Deploy
on:
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Unit tests
        run: curl -L https://se.ifmo.ru/~s367177/update_deploy.php
