name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: backend
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin" --health-interval=10s
          --health-timeout=5s --health-retries=5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Start Backend
        working-directory: backend
        run: npm run start:ci &

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start:
            npm start --prefix frontend
