name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

#      - name: Start Web Server
#        working-directory: frontend
#        run: npm start

      - name: Start Backend
        run: npx ts-node backend/src/index.ts &

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start:
            npm start --prefix frontend