# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches:
      - "**"
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run ESLint for frontend
        working-directory: frontend
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: false

      - name: Install dependencies for backend
        run: npm ci
        working-directory: backend

      - name: Run ESLint for backend
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
          run: npx eslint .
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --format @microsoft/eslint-formatter-sarif
            --output-file eslint-results-backend.sarif
          working-directory: backend
      - name: Upload analysis results to GitHub for frontend
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: frontend/eslint-results-frontend.sarif

      - name: Upload analysis results to GitHub for backend
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: backend/eslint-results-backend.sarif
